# Generated by Django 4.2.16 on 2026-05-16 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_visitante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(blank=True, default='CC', max_length=10, null=True)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vigilante.area')),
                ('id_asistencia_sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.asistenciasede')),
            ],
            options={
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='RegistroManual',
            fields=[
                ('id_registro_manual', models.BigAutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('cedula', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('id_asistencia_sede', models.ForeignKey(blank=True, db_column='id_asistencia_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.asistenciasede')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_manual',
            },
        ),
    ]
