# Generated by Django 4.2.16 on 2026-05-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_ficha',
            field=models.ForeignKey(blank=True, db_column='id_ficha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.ficha'),
        ),
    ]
