# Generated by Django 4.2.16 on 2026-05-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaAmbiente',
            fields=[
                ('id_asistencia_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asistencia_ambiente',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'competencia',
            },
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id_coordinacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_coordinacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'coordinacion',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ficha', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ficha',
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(blank=True, max_length=50, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'jornada',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_programa', models.CharField(blank=True, max_length=255, null=True)),
                ('id_coordinacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.coordinacion')),
            ],
            options={
                'db_table': 'programa',
            },
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id_resultado_aprendizaje', models.AutoField(db_column='id_Resultado_Aprendizaje', primary_key=True, serialize=False)),
                ('resultado_aprendizaje', models.TextField(blank=True, db_column='Resultado_Aprendizaje', null=True)),
                ('id_competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.competencia')),
            ],
            options={
                'db_table': 'resultado_aprendizaje',
            },
        ),
        migrations.CreateModel(
            name='ProgramaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.competencia')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.programa')),
            ],
            options={
                'db_table': 'programa_competencia',
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id_novedad', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo_adjunto', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('id_coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_coordinador', to=settings.AUTH_USER_MODEL)),
                ('id_ficha', models.ForeignKey(blank=True, db_column='id_ficha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.ficha')),
                ('id_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novedades_instructor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'novedad',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('soporte', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_asistencia_ambiente', models.ForeignKey(blank=True, db_column='id_asistencia_ambiente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.asistenciaambiente')),
            ],
            options={
                'db_table': 'justificacion',
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='id_jornada',
            field=models.ForeignKey(blank=True, db_column='id_jornada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.jornada'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='id_programa',
            field=models.ForeignKey(blank=True, db_column='id_programa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.programa'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='id_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.programa'),
        ),
        migrations.CreateModel(
            name='AsistenciaSede',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(blank=True, max_length=255, null=True)),
                ('id_instructor', models.BigIntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencia_sede',
            },
        ),
        migrations.AddField(
            model_name='asistenciaambiente',
            name='id_competencia',
            field=models.ForeignKey(blank=True, db_column='id_competencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coordinador.competencia'),
        ),
        migrations.AddField(
            model_name='asistenciaambiente',
            name='id_instructor',
            field=models.ForeignKey(blank=True, db_column='id_instructor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asistencias_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistenciaambiente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FichaInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coordinador.ficha')),
                ('id_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ficha_instructor',
                'unique_together': {('id_ficha', 'id_instructor')},
            },
        ),
    ]
