# Generated by Django 6.0.2 on 2026-05-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id_huella', models.AutoField(primary_key=True, serialize=False)),
                ('datos_huella_dactilar', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tiene_huella', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'huella',
            },
        ),
        migrations.CreateModel(
            name='registro_actividad',
            fields=[
                ('id_registro_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_actividad',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
