# Generated by Django 6.0.2 on 2026-05-17 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_usuarios', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFallos',
            fields=[
                ('id_fallo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_fallo', models.CharField(choices=[('HUELLA_FALLIDA', 'Huella no coincide'), ('SIN_HUELLA', 'Usuario sin huella registrada'), ('LECTOR_ERROR', 'Error en el lector biométrico'), ('TIMEOUT', 'Tiempo excedido'), ('USUARIO_NO_EXISTE', 'Usuario no registrado en el sistema')], max_length=50)),
                ('cedula_intentada', models.CharField(blank=True, max_length=191, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_fallos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
